### ISSUE TITLE
Game version: 1.11.5 ; skaterboy / girl respawn dislocation

### ISSUE THREAD

**Issue by zeThijs** [dysphie/nmrih-qol-ex#2]
In the latest nmrih update 1.11.5: Skater- boy/girl 'fixes' (respawns) the player on a respawn location, and not on their current location.

**Comment by dysphie** [comment]
`sm_skaterboy` is no longer part of QOL, make sure you've updated to the latest version.

**Comment by zeThijs** [comment]
Alright, thanks for the clarification.

**Comment by dysphie** [comment]
I was in a hurry before so I didn't explain the reasoning, basically, the command hasn't done anything since late 2018. It existed to fix jittery motion after a player alt-tabbed or started recording a demo, but this issue was fixed in NMRiH 1.10.0. Any other usage was merely placebo. There were a few exploits related to using the command in specific scenarios to get an unfair advantage, so it wasn't worth keeping in.
